server:
  port: 8082
mybatis:
  type-aliases-package: com.alvinlkk.tx.pojo
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.100.1.85:3306/alvin_demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
