server:
  port: 8888
  tomcat:
    threads:
      ## tomcat线程最大数量
      max: 1000
    ## 开启tomcat监控
    mbeanregistry:
      enabled: true

## 打开所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"